---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - cd /carbonbond
  - git stash
  - git pull --rebase
  - git stash pop
  - /root/.cargo/bin/rustup default nightly-2020-11-12
  - /root/.cargo/bin/cargo --version
  - pwd
  - echo $PATH
  - echo $HOME
  - export PATH="/root/.cargo/bin:$PATH"
  - echo $PATH
  - /root/.cargo/bin/cargo build --release
  - cd /carbonbond/frontend
  - npx webpack -p
  - cd /carbonbond/
  - cp carbonbond.service /etc/systemd/system/carbonbond.service
  - systemctl daemon-reload
  - systemctl enable carbonbond.service
  - systemctl restart carbonbond.service

trigger:
  branch:
  - master
  event:
  - push
