query Me {
	me {
		name,
		energy,
		invitationCredit
	}
}

query Invitation($code: ID!) {
	invitation(code: $code) {
		code,
		inviterName,
		inviteeEmail,
		words,
		isUsed
	}
}

query CategoriesOfBoard($board_name: String!) {
	board(name: $board_name) {
		categories {
			body
		}
	}
}

query ArticleDetail($id: ID!) {
	article(id: $id) {
		id, title, energy,
		createTime, rootId, content,
		category { body },
		board { boardName }
		author { userName, energy }
	}
}

fragment ArticleMeta on Article {
	id
	title
	category { body }
	author { userName }
	energy
	createTime
	content
	board { boardName }
}

query ArticleList($board_name: String!, $page_size: Int!, $offset: Int!, $show_hidden: Boolean) {
	articleList(
		boardName: $board_name,
		pageSize: $page_size,
		offset: $offset,
		showHidden: $show_hidden
	) {
		...ArticleMeta
	}
}

fragment BoardMeta on Board {
	id, boardName, title, rulingPartyId
}

query BoardList($ids: [ID!]) {
	boardList(ids: $ids) { ...BoardMeta }
}

fragment PartyMeta on Party {
	id, partyName, boardId, energy, chairmanId
}
query MyPartyList($board_name: String) {
    myPartyList(boardName: $board_name) { ...PartyMeta }
}

query PartyDetail($name: String!) {
	party(partyName: $name) {
		id, partyName, boardId,
		energy, chairmanId, position,
		board { boardName }
	}
}