services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=carbonbond
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - carbonbond-net
  redis:
    image: redis:alpine
    restart: always
    networks:
      - carbonbond-net
  frontend:
    image: "carbonbond/frontend:${TAG:-latest}"
    # 欲自行建置 docker image ，以下三行取代上一行
    # build:
    #   context: ../frontend/app/desktop
    #   dockerfile: ../frontend/app/desktop/deploy/Dockerfile
    restart: always
    ports:
      - ${FRONTEND_PORT:-80}:80
    networks:
      - carbonbond-net
  api-service:
    image: "carbonbond/api-service:${TAG:-latest}"
    # 欲自行建置 docker image ，以下三行取代上一行
    # build:
    #   context: ../api-service
    #   dockerfile: ../api-service/deploy/Dockerfile
    volumes:
      - ../api-service/config:/app/api-service/config
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - carbonbond-net
volumes:
  postgres-data: {}

networks:
  carbonbond-net:
    driver: bridge