services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=carbonbond
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: always
    ports:
      - 5432:5432
    networks:
      - carbonbond-net
  redis:
    image: redis:alpine
    restart: always
    networks:
      - carbonbond-net
  frontend:
    image: carbonbond/frontend:latest
    # 欲自行建置 docker image ，以下三行取代上一行
    # build:
    #   context: ../frontend
    #   dockerfile: deploy/Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - carbonbond-net
  api-service:
    image: carbonbond/api-service:latest
    # 欲自行建置 docker image ，以下三行取代上一行
    # build:
    #   context: ../api-service
    #   dockerfile: deploy/Dockerfile
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - carbonbond-net
volumes:
  postgres-data: {}

networks:
  carbonbond-net:
    driver: bridge