# 若本地環境與此設定檔有出入，請勿直接修改本檔案，應另創建一份 carbonbond.dev.toml 設定檔

[server]
address = "127.0.0.1"
port = 8080
# mailgun_key_file 為一個檔案位置
mailgun_key_file = "config/secret/MAILGUN_KEY.example"
base_url = "http://localhost:8080"
mail_domain = "mail.carbon-bond.com"
mail_from = "碳鍵 <noreply@mail.carbon-bond.com>"

[database]
# url 的格式為 "postgres://[用戶名]:[密碼]@[資料庫位址]:[埠口]/[資料庫名]"
# url = "postgres://postgres@localhost:5432/carbonbond"
dbname = "carbonbond"
username = "carbonbond"
password = "carbonbond"
port = 5432
host = "localhost"
data_path = "data"
max_conn = 10

[redis]
host = "redis://127.0.0.1/"

[user]
email_whitelist = [
    # 臺大
    '@ntu\.edu\.tw$',
    # 清大
    '@(oz|m\d{2,3})\.nthu\.edu\.tw$',
    # 交大
    '@nctu\.edu\.tw$',
    # 成大
    '@mail\.ncku\.edu\.tw$',
    # 政大
    '@nccu\.edu\.tw$',
    # 中央
    '@cc\.ncu\.edu\.tw$',
    # 中興
    '@mail\.nchu\.edu\.tw$',
    # 中山
    '@student\.nsysu\.edu\.tw$',
    # 中正
    '@ccu\.edu\.tw$',
    # 臺師大
    '@ntnu\.edu\.tw$',
    # 高師大
    '@mail\.nknu\.edu\.tw$'
]