# 若本地環境與此設定檔有出入，請勿直接修改本檔案，應另創建一份 carbonbond.dev.toml 設定檔

[server]
address = "127.0.0.1"
port = 8080
# base_url 為前端網址（若反向代理，前端、後端的 IP 跟埠口可能不同）
base_url = "http://localhost:3000"
# mailgun_key_file 為一個檔案位置
mailgun_key_file = "config/secret/MAILGUN_KEY.example"
mail_domain = "mail.carbonbond.monster"
mail_from = "碳鍵 <noreply@mail.carbonbond.monster>"

[database]
# url 的格式為 "postgres://[用戶名]:[密碼]@[資料庫位址]:[埠口]/[資料庫名]"
# url = "postgres://postgres:mypassword@localhost:5432/carbonbond"
dbname = "carbonbond"
username = "postgres"
password = "mypassword"
port = 5432
host = "localhost"
data_path = "data"
max_conn = 10

[redis]
host = "redis://127.0.0.1/"

[account]
# 信件將一律寄送至 fake_email
# 開發可將 fake_email 設爲自己的常用信箱，以避免誤寄
# 上線時應移除此設置
fake_email = "fake@email"
allow_self_signup = true
allow_invitation_signup = true
min_password_length = 6
max_password_length = 100
email_whitelist = [
    # 臺大
    '@ntu\.edu\.tw$',
    # 清大
    '@(oz|m\d{2,3})\.nthu\.edu\.tw$',
    # 交大
    '@nctu\.edu\.tw$',
    # 成大
    '@mail\.ncku\.edu\.tw$',
    # 政大
    '@nccu\.edu\.tw$',
    # 中央
    '@cc\.ncu\.edu\.tw$',
    # 中興
    '@mail\.nchu\.edu\.tw$',
    # 中山
    '@student\.nsysu\.edu\.tw$',
    # 中正
    '@ccu\.edu\.tw$',
    # 臺師大
    '@ntnu\.edu\.tw$',
    # 高師大
    '@mail\.nknu\.edu\.tw$'
]