[server]
address = "0.0.0.0"
port = 8080
# base_url 為前端網址（若反向代理，前端、後端的 IP 跟埠口可能不同）
base_url = "http://localhost"
# mailgun_key_file 為一個檔案位置
mailgun_key_file = "config/secret/MAILGUN_KEY"
mail_domain = "mail.carbonbond.monster"
mail_from = "碳鍵 <noreply@mail.carbonbond.monster>"

[database]
# url 的格式為 "postgres://[用戶名]:[密碼]@[資料庫位址]:[埠口]/[資料庫名]"
# url = "postgres://postgres:mypassword@postgres:5432/carbonbond"
dbname = "carbonbond"
username = "postgres"
password = "mypassword"
port = 5432
host = "postgres"
data_path = "data"
max_conn = 10

[redis]
host = "redis://redis/"

[account]
allow_self_signup = true
allow_invitation_signup = true
session_expire_seconds = 604800
min_password_length = 6
max_password_length = 100
email_whitelist = [
    '@ntu\.edu\.tw$',
    '@(oz|m\d{2,3})\.nthu\.edu\.tw$',
    '@nctu\.edu\.tw$',
    '@mail\.ncku\.edu\.tw$',
    '@nccu\.edu\.tw$',
    '@cc\.ncu\.edu\.tw$',
    '@mail\.nchu\.edu\.tw$',
    '@ccu\.edu\.tw$',
    '@ntnu\.edu\.tw$',
    '@mail\.nknu\.edu\.tw$'
]

[business]
advertisement_contact_mail = "business@carbonbond.monster"