[server]
address = "0.0.0.0"
port = 8080
base_url = "http://localhost"

[email]
domain = "mail.my-domain.com"
from = "碳鍵 <noreply@mail.my-domain.com>"
# fake_receiver = "fake-receiver@email"
signup_whitelist = []
    [email.driver]
    type = "Log"

[database]
# url 的格式為 "postgres://[用戶名]:[密碼]@[資料庫位址]:[埠口]/[資料庫名]"
# url = "postgres://postgres:mypassword@postgres:5432/carbonbond"
dbname = "carbonbond"
username = "postgres"
password = "mypassword"
port = 5432
host = "postgres"
data_path = "data"
max_conn = 10

[redis]
host = "redis://redis/"

[account]
allow_self_signup = true
allow_invitation_signup = true
session_expire_seconds = 604800
min_password_length = 6
max_password_length = 100

[business]
advertisement_contact_mail = "business@my-domain.com"