schema {
    query: Query
    mutation: Mutation
}

type Category {
    id: ID!
    body: String!
    isActive: Boolean!
    board: Board! @juniper(ownership: "owned")
}

type Board {
    id: ID!
    boardName: String!
    categories: [Category!]! @juniper(ownership: "owned")
    title: String!
    detail: String!
    rulingPartyId: ID!
    articleCount(showHidden: Boolean): Int! @juniper(ownership: "owned")
    parties: [Party!]! @juniper(ownership: "owned")
}

type Party {
    id: ID!
    partyName: String!
    chairmanId: String!
    boardId: ID
    energy: Int!
    position(userId: String): Int! @juniper(ownership: "owned")
    board: Board @juniper(ownership: "owned")
}

type Article {
	id: ID!
    title: String!
    authorId: String!
    energy: Int!
    createTime: Int!
    rootId: ID!
    content: [String!]! @juniper(ownership: "owned")
    category: Category! @juniper(ownership: "owned")
	board: Board! @juniper(ownership: "owned")
    sameRootArticles: [Article!]! @juniper(ownership: "owned")
}

type Me {
    id: String
}

type Query {
    me: Me! @juniper(ownership: "owned")

    myPartyList(boardName: String): [Party!]! @juniper(ownership: "owned")
    party(partyName: String!): Party! @juniper(ownership: "owned")

    board(name: String!): Board! @juniper(ownership: "owned")
    boardList(ids: [ID!]): [Board!]! @juniper(ownership: "owned")

    article(id: ID!): Article! @juniper(ownership: "owned")
    articleList(
        boardName: String!
        offset: Int!
        pageSize: Int!
        showHidden: Boolean
    ): [Article!]! @juniper(ownership: "owned")

    checkBoardNameValid(name: String!): String @juniper(ownership: "owned")
    checkPartyNameValid(name: String!): String @juniper(ownership: "owned")
    checkArticleContentValid(content: [String!]!boardName: String!categoryName: String!): [String]! @juniper(ownership: "owned")
}

input Reply {
    articleId: ID!
    transfuse: Int!
}

type Mutation {
	createArticle(
		boardName: String!
		categoryName: String!
		title: String!
		content: [String!]!
		replyTo: [Reply!]!
	): ID! @juniper(ownership: "owned")

    createParty(partyName: String! boardName: String): ID! @juniper(ownership: "owned")
    createBoard(boardName: String! partyName: String!): ID! @juniper(ownership: "owned")

    login(id: String! password: String!): Boolean! @juniper(ownership: "owned")
    logout: Boolean! @juniper(ownership: "owned")
    inviteSignup(email: String!): Boolean! @juniper(ownership: "owned")
    signupByInvitation(code: String! id: String! password: String!): Boolean! @juniper(ownership: "owned")
}