name: api-service-build-dev

on:
  push:
    branches: [ master ]
    paths:
      - 'api-service/**'

defaults:
  run:
    shell: bash
    working-directory: ./api-service

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: ./api-service
    - name: 編譯
      run: sh ./build.sh
    - name: 登入 DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 建構並推送 docker 映像檔
      uses: docker/build-push-action@v2
      with:
        context: ./api-service
        push: true
        tags: carbonbond/api-service:latest
        file: ./api-service/deploy/Dockerfile
    - name: 佈屬到開發環境
      if: ${{ success() }}
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.DEV_WEBHOOK_URL }}/hooks/redeploy-api-service
        webhook_secret: ${{ secrets.DEV_WEBHOOK_SECRET }}
        verify_ssl: false
        verbose: true
