name: frontend-build-production

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: c-hive/gha-yarn-cache@v2 
      with:
        directory: ./frontend
    - run: yarn install
    - run: yarn build
    - name: 登入 DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 建構並推送 docker 映像檔
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: carbonbond/frontend:stable
        file: ./frontend/deploy/Dockerfile
    - name: 佈屬到開發環境
      if: ${{ success() }}
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.PRODUCTION_WEBHOOK_URL }}/hooks/redeploy-frontend
        webhook_secret: ${{ secrets.PRODUCTION_WEBHOOK_SECRET }}
        verify_ssl: false
        verbose: true
