# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

defaults:
  run:
    shell: bash
    working-directory: ./frontend

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - run: yarn lint
    - run: yarn build
    - run: yarn check-ts
    - run: yarn check-css

