# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

defaults:
  run:
    shell: bash
    working-directory: ./frontend


on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: check-ts
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: check-css
