name: Node.js CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'

defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  frontend-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: c-hive/gha-yarn-cache@v2
      with:
        directory: ./frontend
    - run: yarn install
    - run: yarn lint
    - run: yarn workspace web build
    - run: yarn workspace web check-ts
    - run: yarn workspace web check-css
    - run: yarn workspace web test

