name: release

on:
  release:
    types: [ published ]
  push:
    branches: [ release ]
    working-directory: ./frontend

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn build
    - name: Log in to the Container registry
      uses: docker/login-action@1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: carbonbond/frontend:latest
        file: ./deploy/Dockerfile
