name: release

on:
  release:
    types: [ published ]
  push:
    branches: [ release ]

defaults:
  run:
    shell: bash
    working-directory: ./frontend

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: c-hive/gha-yarn-cache@v2 
      with:
        directory: ./frontend
    - run: yarn install
    - run: yarn build
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: carbonbond/frontend:latest
        file: ./frontend/deploy/Dockerfile
        context: ./frontend
