name: Rust

on:
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: ./carbonbond

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: carbonbond
          POSTGRES_PASSWORD: carbonbond
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Prepare DB
      run: cargo run --verbose --features prepare --bin prepare -- -m
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
