name: Rust

on:
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: ./carbonbond

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      run: cargo build --verbose
      env:
        SQLX_OFFLINE: true
    - name: Run tests
      run: cargo test --verbose
